//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFalabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_asesores
    {
        public string pk_id_asesor { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string email { get; set; }
    }
}
