//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFalabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empresas_productos
    {
        public int id { get; set; }
        public string fk_codigo_empresa { get; set; }
        public string fk_codigo_producto { get; set; }
    }
}
