//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFalabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pedidos
    {
        public int pk_id_pedido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string codigo_empresa { get; set; }
        public Nullable<int> total_costo { get; set; }
        public string observaciones { get; set; }
        public string codigo_asesor { get; set; }
        public int status { get; set; }
    }
}
